### ISSUE TITLE
updateLabels method

### ISSUE THREAD

**Issue by davelandry** [superleap/github-issues-label-sync#43]
**What is the current behavior?**
When syncing with a repository, I am currently fetching the existing labels, comparing that list to my configuration, deleting the ones not in my config and creating the new ones. However, if I wanted to just change the color of one of the labels, I would need to completely remove it and create a new one (correct me if I'm wrong). This is less than desirable, as it will untag any issue associated with the old colored label.

**What is the expected behavior?**
It would be great if there was a method to match labels on their names, and simply update their colors as needed (so that they remained tagged to issues).

**Comment by vrtxf** [comment]
Hi again, I added 2 methods, `updateLabel` and `updatelabels` as documented in https://mikedeboer.github.io/node-github/#api-issues-updateLabel and https://developer.github.com/v3/issues/labels/#update-a-label
Hope this is what you were looking for !
Cheers
